ROBOHEART_VERSION = c1a7b773c68f7ce6ec25209f62f0b144a483e570
ROBOHEART_SITE = $(call github,ftCommunity,roboheart,$(ROBOHEART_VERSION))
ROBOHEART_LICENSE = GPL-3.0-only
ROBOHEART_SRC_SUBDIR = github.com/ftCommunity/roboheart
ROBOHEART_BUILD_TARGETS = cmd/roboheart

ifeq ($(BR2_PACKAGE_ROBOHEART_ALL_SERVICES),y)
	ROBOHEART_CHECKDEPS_ARGS += -a
else
	ifeq ($(BR2_PACKAGE_ROBOHEART_SERVICE_ACM),y)
        	ROBOHEART_CHECKDEPS_ARGS += --acm
    endif
	ifeq ($(BR2_PACKAGE_ROBOHEART_SERVICE_CONFIG),y)
        	ROBOHEART_CHECKDEPS_ARGS += --config
    endif
	ifeq ($(BR2_PACKAGE_ROBOHEART_SERVICE_DEVINFO),y)
        	ROBOHEART_CHECKDEPS_ARGS += --deviceinfo
    endif
    ifeq ($(BR2_PACKAGE_ROBOHEART_SERVICE_FS),y)
         	ROBOHEART_CHECKDEPS_ARGS += --filesystem
    endif
	ifeq ($(BR2_PACKAGE_ROBOHEART_SERVICE_FWVER),y)
        	ROBOHEART_CHECKDEPS_ARGS += --fwver
    endif
	ifeq ($(BR2_PACKAGE_ROBOHEART_SERVICE_LOCALE),y)
        	ROBOHEART_CHECKDEPS_ARGS += --locale
    endif
	ifeq ($(BR2_PACKAGE_ROBOHEART_SERVICE_RELVER),y)
        	ROBOHEART_CHECKDEPS_ARGS += --releasever
    endif
	ifeq ($(BR2_PACKAGE_ROBOHEART_SERVICE_POWER),y)
        	ROBOHEART_CHECKDEPS_ARGS += --power
    endif
	ifeq ($(BR2_PACKAGE_ROBOHEART_SERVICE_WEB),y)
        	ROBOHEART_CHECKDEPS_ARGS += --web
    endif
	ifeq ($(BR2_PACKAGE_ROBOHEART_SERVICE_VNCSERVER),y)
        	ROBOHEART_CHECKDEPS_ARGS += --vncserver
    endif
endif

define ROBOHEART_POST_CONFIGURE_CHECK_SERVICE_DEPENDENCIES
	cd $(@D) && go run cmd/setservices/*.go $(ROBOHEART_CHECKDEPS_ARGS) && make checkdeps
endef

ROBOHEART_POST_CONFIGURE_HOOKS += ROBOHEART_POST_CONFIGURE_SET_BUILD_OPTIONS ROBOHEART_POST_CONFIGURE_CHECK_SERVICE_DEPENDENCIES

define ROBOHEART_PRE_BUILD_VENDORING
    cd $(@D) && go mod vendor
endef

ROBOHEART_PRE_BUILD_HOOKS += ROBOHEART_PRE_BUILD_VENDORING

$(eval $(golang-package))
