ROOTFS_TXTZIP_OUT_NAME := txt
ROOTFS_TXTZIP_DEPENDENCIES := host-python3 host-zip rootfs-initramfs rootfs-squashfs

ifeq ($(BR2_TARGET_ROOTFS_TXTZIP_CUSTOM_NAME_SOURCE_STRING), y)
	ROOTFS_TXTZIP_OUT_NAME := $(BR2_TARGET_ROOTFS_TXTZIP_CUSTOM_NAME_NAME)
endif

ifeq ($(BR2_TARGET_ROOTFS_TXTZIP_CUSTOM_NAME_SOURCE_FILE), y)
	ROOTFS_TXTZIP_OUT_NAME := $(BR2_TARGET_ROOTFS_TXTZIP_CUSTOM_NAME_PREFIX)
	ROOTFS_TXTZIP_OUT_NAME := $(ROOTFS_TXTZIP_OUT_NAME)$(shell cat ${BR2_TARGET_ROOTFS_TXTZIP_CUSTOM_NAME_SOURCE_FILE_NAME})
	ROOTFS_TXTZIP_OUT_NAME := $(ROOTFS_TXTZIP_OUT_NAME)$(BR2_TARGET_ROOTFS_TXTZIP_CUSTOM_NAME_SUFFIX)
endif

ifneq ($(BR2_TARGET_ROOTFS_TXTZIP_CUSTOM_NAME), y)
	BR2_TARGET_ROOTFS_TXTZIP_CUSTOM_NAME_EXTENSION := zip
endif

define ROOTFS_TXTZIP_CMD
	python3 $(BR2_EXTERNAL_FTCOMMUNITY_TXT_PATH)/fs/txtzip/build.py $(BR2_TARGET_ROOTFS_TXTZIP_FILES) $(ROOTFS_TXTZIP_DIR) $(ROOTFS_TXTZIP_OUT_NAME) $(BR2_TARGET_ROOTFS_TXTZIP_CUSTOM_NAME_EXTENSION) $(BINARIES_DIR)
endef


$(eval $(rootfs))
